version: '3.8'
services:
  galepages:
    build:
     context: .
     dockerfile: Dockerfile 
    image: galepages:v1
    container_name: apache
    volumes:
      - "/var/www/html/galepages:/var/www/html/galepages"
      - "/etc/httpd/conf/httpd-galepages.conf:/etc/httpd/conf.d/httpd-galepages.conf"
      - "/var/log/httpd:/var/log/httpd"
    ports:
      - "9187:9187"
