#!/bin/bash

### BEGIN INIT INFO
# Provides:          php-fpm
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php-fpm daemon
# Description:       starts php-fpm daemon
### END INIT INFO

#. /lib/lsb/init-functions

CONFIG=/etc/php-fpm.conf
DAEMON=/usr/sbin/php-fpm
DESC="php-fpm daemon"
PID=/run/php-fpm/php-fpm.pid

test -x $DAEMON || exit 0
test -d $CONFIG_DIR || exit 0

function start {
    $DAEMON -c $CONFIG &> /dev/null
}

function stop {
#    killall php-fpm &> /dev/null
    kill `cat /run/php-fpm/php-fpm.pid 2>/dev/null` &> /dev/null
}

kill -0 `cat /run/php-fpm/php-fpm.pid 2>/dev/null` &> /dev/null
running=$?
case $1 in
start)
    if [ 0 -eq $running ]; then
        echo "php-fpm daemon is already running"
        exit
    fi
    start && echo "php-fpm daemon started"
;;
stop)
    if [ 0 -ne $running ]; then
        echo "php-fpm daemon is not running"
        exit
    fi
    stop && echo "php-fpm daemon was stoped"
;;
restart)
    stop && start;
    echo "php-fpm daemon restarted"
;;
status)
    if [ 0 -eq $running ]; then
        echo "php-fpm daemon is running"
    else
        echo "php-fpm daemon is not running"
    fi
;;
*)
    echo "$0 [start|stop|restart|status]"
;;
esac
